/*
** This file is intended only to allow zic.c to compile.
** Compilations made with this should not be distributed, since
** the below information is fairly useful in distributions.
**
** This file should always be distributed included in the
** DateTime::Timezones repository, as it isn't autogenerated.
*/
static char const PKGVERSION[]="";
static char const TZVERSION[]="";
static char const REPORT_BUGS_TO[]="";
